#!/usr/bin/env bash
set -e

title=$(date +%Y-%m-%d)

number=$(gh issue list --search "${title} in:title" --json number --jq "first.number")

if [ -z "${number}" ]
then
  number=$(gh issue create --title "${title}" --body "" | sed --null-data --regexp-extended --expression "s;.*issues/([0-9]+);\1;")
fi

gh issue view "${number}" --web
